export const subscriptionManagerAbi = [
  {
    type: "event",
    name: "PlanRegistered",
    inputs: [
      { name: "planKey", type: "bytes32", indexed: true },
      { name: "author", type: "address", indexed: true },
      { name: "paymentAsset", type: "uint8", indexed: false },
      { name: "token", type: "address", indexed: true },
      { name: "price", type: "uint256", indexed: false },
      { name: "periodSeconds", type: "uint64", indexed: false },
      { name: "externalId", type: "bytes32", indexed: false },
    ],
  },
  {
    type: "event",
    name: "PlanUpdated",
    inputs: [
      { name: "planKey", type: "bytes32", indexed: true },
      { name: "author", type: "address", indexed: true },
      { name: "paymentAsset", type: "uint8", indexed: false },
      { name: "token", type: "address", indexed: true },
      { name: "price", type: "uint256", indexed: false },
      { name: "periodSeconds", type: "uint64", indexed: false },
      { name: "active", type: "bool", indexed: false },
      { name: "externalId", type: "bytes32", indexed: false },
    ],
  },
  {
    type: "event",
    name: "SubscriptionPaid",
    inputs: [
      { name: "planKey", type: "bytes32", indexed: true },
      { name: "subscriber", type: "address", indexed: true },
      { name: "author", type: "address", indexed: true },
      { name: "paymentAsset", type: "uint8", indexed: false },
      { name: "token", type: "address", indexed: false },
      { name: "amount", type: "uint256", indexed: false },
      { name: "platformFee", type: "uint256", indexed: false },
      { name: "paidUntil", type: "uint256", indexed: false },
    ],
  },
  {
    type: "function",
    name: "plans",
    stateMutability: "view",
    inputs: [{ name: "planKey", type: "bytes32" }],
    outputs: [
      { name: "author", type: "address" },
      { name: "paymentAsset", type: "uint8" },
      { name: "token", type: "address" },
      { name: "price", type: "uint256" },
      { name: "periodSeconds", type: "uint64" },
      { name: "active", type: "bool" },
      { name: "externalId", type: "bytes32" },
    ],
  },
  {
    type: "function",
    name: "paidUntil",
    stateMutability: "view",
    inputs: [
      { name: "subscriber", type: "address" },
      { name: "planKey", type: "bytes32" },
    ],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "registerPlan",
    stateMutability: "nonpayable",
    inputs: [
      { name: "planKey", type: "bytes32" },
      { name: "paymentAsset", type: "uint8" },
      { name: "token", type: "address" },
      { name: "price", type: "uint256" },
      { name: "periodSeconds", type: "uint64" },
      { name: "externalId", type: "bytes32" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "updatePlan",
    stateMutability: "nonpayable",
    inputs: [
      { name: "planKey", type: "bytes32" },
      { name: "paymentAsset", type: "uint8" },
      { name: "token", type: "address" },
      { name: "price", type: "uint256" },
      { name: "periodSeconds", type: "uint64" },
      { name: "active", type: "bool" },
      { name: "externalId", type: "bytes32" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "subscribe",
    stateMutability: "payable",
    inputs: [{ name: "planKey", type: "bytes32" }],
    outputs: [{ name: "nextPaidUntil", type: "uint256" }],
  },
] as const;
