export const platformSubscriptionManagerAbi = [
  {
    type: "event",
    name: "TierRegistered",
    inputs: [
      { name: "tierKey", type: "bytes32", indexed: true },
      { name: "price", type: "uint256", indexed: false },
      { name: "baseStorageGb", type: "uint16", indexed: false },
      { name: "maxExtraStorageGb", type: "uint16", indexed: false },
      { name: "pricePerExtraGb", type: "uint256", indexed: false },
      { name: "periodSeconds", type: "uint64", indexed: false },
    ],
  },
  {
    type: "event",
    name: "TierUpdated",
    inputs: [
      { name: "tierKey", type: "bytes32", indexed: true },
      { name: "price", type: "uint256", indexed: false },
      { name: "baseStorageGb", type: "uint16", indexed: false },
      { name: "maxExtraStorageGb", type: "uint16", indexed: false },
      { name: "pricePerExtraGb", type: "uint256", indexed: false },
      { name: "periodSeconds", type: "uint64", indexed: false },
      { name: "active", type: "bool", indexed: false },
    ],
  },
  {
    type: "event",
    name: "PlatformSubscriptionPaid",
    inputs: [
      { name: "author", type: "address", indexed: true },
      { name: "tierKey", type: "bytes32", indexed: true },
      { name: "extraStorageGb", type: "uint16", indexed: false },
      { name: "totalStorageGb", type: "uint16", indexed: false },
      { name: "amount", type: "uint256", indexed: false },
      { name: "paidUntil", type: "uint256", indexed: false },
    ],
  },
  {
    type: "function",
    name: "paymentToken",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
  },
  {
    type: "function",
    name: "platformTreasury",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
  },
  {
    type: "function",
    name: "tiers",
    stateMutability: "view",
    inputs: [{ name: "tierKey", type: "bytes32" }],
    outputs: [
      { name: "price", type: "uint256" },
      { name: "baseStorageGb", type: "uint16" },
      { name: "maxExtraStorageGb", type: "uint16" },
      { name: "pricePerExtraGb", type: "uint256" },
      { name: "periodSeconds", type: "uint64" },
      { name: "active", type: "bool" },
    ],
  },
  {
    type: "function",
    name: "paidUntil",
    stateMutability: "view",
    inputs: [
      { name: "author", type: "address" },
      { name: "tierKey", type: "bytes32" },
    ],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "registerTier",
    stateMutability: "nonpayable",
    inputs: [
      { name: "tierKey", type: "bytes32" },
      { name: "price", type: "uint256" },
      { name: "baseStorageGb", type: "uint16" },
      { name: "maxExtraStorageGb", type: "uint16" },
      { name: "pricePerExtraGb", type: "uint256" },
      { name: "periodSeconds", type: "uint64" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "updateTier",
    stateMutability: "nonpayable",
    inputs: [
      { name: "tierKey", type: "bytes32" },
      { name: "price", type: "uint256" },
      { name: "baseStorageGb", type: "uint16" },
      { name: "maxExtraStorageGb", type: "uint16" },
      { name: "pricePerExtraGb", type: "uint256" },
      { name: "periodSeconds", type: "uint64" },
      { name: "active", type: "bool" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "subscribe",
    stateMutability: "nonpayable",
    inputs: [
      { name: "tierKey", type: "bytes32" },
      { name: "extraStorageGb", type: "uint16" },
    ],
    outputs: [{ name: "nextPaidUntil", type: "uint256" }],
  },
  {
    type: "function",
    name: "calculateAmount",
    stateMutability: "view",
    inputs: [
      { name: "tierKey", type: "bytes32" },
      { name: "extraStorageGb", type: "uint16" },
    ],
    outputs: [{ name: "", type: "uint256" }],
  },
] as const;
